-- board 계정 생성
CREATE USER board IDENTIFIED BY java1234;

-- 권한 부여
GRANT CONNECT, RESOURCE TO board;

-- 테이블스페이스 용량 제한 해제
ALTER USER board QUOTA UNLIMITED ON USERS;

-- 회원
CREATE TABLE MEMBER (
    MEMBER_SEQ    NUMBER PRIMARY KEY,
    NAME          VARCHAR2(50)  NOT NULL,
    ID            VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD      VARCHAR2(100) NOT NULL,
    JUMIN         VARCHAR2(14)  NOT NULL,
    NICKNAME      VARCHAR2(50)  NOT NULL UNIQUE,
    EMAIL         VARCHAR2(100),
    PHONE         VARCHAR2(20),
    ADDRESS       VARCHAR2(200),
    ROLE          VARCHAR2(10)  DEFAULT 'user',
    JOIN_DATE     DATE          DEFAULT SYSDATE,
    UPDATE_DATE   DATE,
    DEL_YN        VARCHAR2(1)   DEFAULT 'N'
);

-- 게시판
CREATE TABLE BOARD (
    BOARD_SEQ     NUMBER PRIMARY KEY,
    TITLE         VARCHAR2(200) NOT NULL,
    CONTENT       CLOB          NOT NULL,
    NICKNAME      VARCHAR2(50)  NOT NULL,
    MEMBER_SEQ    NUMBER        NOT NULL,
    VIEW_COUNT    NUMBER        DEFAULT 0,
    WRITE_DATE    DATE          DEFAULT SYSDATE,
    UPDATE_DATE   DATE,
    DEL_YN        VARCHAR2(1)   DEFAULT 'N',
    FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
);

-- 댓글
CREATE TABLE COMMENTS (
    COMMENTS_SEQ  NUMBER PRIMARY KEY,
    BOARD_SEQ     NUMBER       NOT NULL,
    MEMBER_SEQ    NUMBER       NOT NULL,
    CONTENT       VARCHAR2(500) NOT NULL,
    WRITE_DATE    DATE          DEFAULT SYSDATE,
    DEL_YN        VARCHAR2(1)   DEFAULT 'N',
    FOREIGN KEY (BOARD_SEQ)  REFERENCES BOARD(BOARD_SEQ),
    FOREIGN KEY (MEMBER_SEQ) REFERENCES MEMBER(MEMBER_SEQ)
);

-- 시퀀스
CREATE SEQUENCE MEMBER_SEQ  START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BOARD_SEQ   START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMENTS_SEQ START WITH 1 INCREMENT BY 1;

SELECT column_name, data_type, data_length, nullable
FROM user_tab_columns
WHERE table_name = 'MEMBER'
ORDER BY column_id;

select * from MEMBER;